export const COUNTER_TYPE = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
};

export const EMPLOYEE_TYPE = {
  ADD_EMPLOYEE: "ADD EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE EMPLOYEE",
  STATUS_EMPLOYEE: "STATUS EMPLOYEE",
};
